import { Component } from '@angular/core';
import { MatDialogRef } from '@angular/material/dialog';

@Component({
    selector: 'app-portal-variable-dialogue',
    templateUrl: './portal-variable-dialogue.component.html',
    styleUrls: ['../compatibility.component.scss']
})
export class PortalVariableDialogueComponent {
    constructor(public dialogRef: MatDialogRef<PortalVariableDialogueComponent>) { }

    public lessVariables = {
        '@ColorMenuAccent': '@ColorMenuBackgroundAlpha',
        '@ColorMenuAccentBorder': '@ColorContentAccent',
        '@ColorMenuAccentText': '@ColorMenuTextAlpha',
        '@ColorMenuAccentActive': 'darken(@ColorMenuAccent, 20%)',
        '@ColorMenuAccentTextActive': '@ColorMenuTextAlpha',
        '@ColorMenuAccentHover': 'lighten(@ColorMenuAccent, 20%)',
        '@ColorMenuAccentBorderActive': 'lighten(@ColorMenuAccentBorder, 20%)',
        '@ColorMenuAccentBorderHover': 'lighten(@ColorMenuAccentBorder, 20%)',
        '@ColorMenuAccentTextHover': 'lighten(@ColorMenuAccentText, 20%)',
        '@ColorMenuBackgroundAlpha': '#3E4B5B',
        '@ColorMenuTextAlpha': '#ffffff',
        '@ColorMenuBackgroundBeta': 'darken(@ColorMenuBackgroundAlpha, 30%)',
        '@ColorMenuTextBeta': '@ColorMenuTextAlpha',
        '@ColorFooterBackground': '@ColorMenuBackgroundAlpha',
        '@ColorFooterText': '@ColorMenuTextAlpha',
        '@ColorSiteBackground': '#ffffff',
        '@ColorContentAccent': '#4DC3D6',
        '@ColorContentAccentBorder': 'darken(@ColorContentAccent, 10%)',
        '@ColorContentAccentText': '#192239',
        '@ColorContentBackground': '@ColorSiteBackground',
        '@ColorContentBackgroundActive': 'darken(@ColorSiteBackground, 10%)',
        '@ColorContentBackgroundHover': 'darken(@ColorSiteBackground, 10%)',
        '@ColorContentTextAlpha': '#192239',
        '@ColorContentTextBeta': 'tint(@ColorContentTextAlpha, 40%)',
        '@ColorContentTextLink': '@ColorContentTextAlpha',
        '@ColorContentTextHeader': '@ColorContentTextAlpha',
        '@ColorContentTextLabel': 'lighten(@ColorContentTextAlpha, 10%)',
        '@ColorContentTextCaption': 'lighten(@ColorContentTextAlpha, 10%)',
        '@ColorLineBreak': 'lighten(@ColorContentTextAlpha, 60%)',
        '@ColorPopupOverlay': 'rgba(0,0,0,0.75)',
        '@ColorDialogBackground': '@ColorSiteBackground',
        '@ColorTooltipBackground': '#3E4B5B',
        '@ColorTooltipText': '#fff',
        '@ColorElementShadow': '@ColorPopupOverlay',
        '@ColorAlertBackground': '@ColorContentAccent',
        '@ColorAlertText': '@ColorContentTextAlpha',
        '@ColorInputText': '@ColorContentTextAlpha',
        '@ColorInputBorder': '@ColorInputText',
        '@ColorInputBorderActive': '@ColorContentAccent',
        '@ColorInputBorderDisabled': 'tint(@ColorInputBorder, 60%)',
        '@ColorInputTextDisabled': 'tint(@ColorInputText, 50%)',
        '@ColorInputBackgroundActive': '@ColorContentAccent',
        '@ColorInputBackgroundHover': '@ColorMenuBackgroundAlpha',
        '@ColorContentLoader': '@ColorContentTextAlpha',
        '@ColorAccentLoader': '#fff',
        '@ColorButton': '@ColorSiteBackground',
        '@ColorButtonBorder': '@ColorContentTextAlpha',
        '@ColorButtonText': '@ColorContentTextAlpha',
        '@ColorButtonActive': '@ColorButton',
        '@ColorButtonBorderActive': '@ColorButtonBorder',
        '@ColorButtonTextActive': '@ColorButtonText',
        '@ColorButtonHover': '@ColorButton',
        '@ColorButtonBorderHover': '@ColorButtonBorder',
        '@ColorButtonTextHover': '@ColorButtonText',
        '@ColorButtonDisabled': 'tint(@ColorButton, 60%)',
        '@ColorButtonBorderDisabled': 'tint(@ColorButtonBorder, 60%)',
        '@ColorButtonTextDisabled': 'tint(@ColorButtonText, 36%)',
        '@ColorButtonAccent': '@ColorContentAccent',
        '@ColorButtonAccentBorder': '@ColorContentAccentBorder',
        '@ColorButtonAccentText': '@ColorContentAccentText',
        '@ColorButtonAccentActive': 'darken(@ColorButtonAccent, 10%)',
        '@ColorButtonAccentBorderActive': 'darken(@ColorButtonAccentBorder, 10%)',
        '@ColorButtonAccentTextActive': 'darken(@ColorButtonAccentText, 10%)',
        '@ColorButtonAccentHover': 'lighten(@ColorButtonAccent, 5%)',
        '@ColorButtonAccentBorderHover': 'lighten(@ColorButtonAccentBorder, 5%)',
        '@ColorButtonAccentTextHover': 'lighten(@ColorButtonAccentText, 5%)',
        '@ColorButtonAccentDisabled': 'tint(@ColorButtonAccent, 60%)',
        '@ColorButtonAccentBorderDisabled': 'tint(@ColorButtonAccentBorder, 60%)',
        '@ColorButtonAccentTextDisabled': 'tint(@ColorButtonAccentText, 60%)',
        '@ColorStatusGood': '#B8E986',
        '@ColorStatusGoodText': '@ColorContentTextAlpha',
        '@ColorStatusAlert': '#FFE99F',
        '@ColorStatusAlertText': '@ColorContentTextAlpha',
        '@ColorStatusWarning': '#e22e2e',
        '@ColorStatusWarningText': '@ColorContentTextAlpha',
        '@ColorDataGood': '@ColorStatusGood',
        '@ColorDataGoodText': '@ColorStatusGoodText',
        '@ColorDataGoodLesser': 'lighten(@ColorDataGood, 20%)',
        '@ColorDataMedian': '@ColorStatusAlert',
        '@ColorDataMedianText': '@ColorStatusAlertText',
        '@ColorDataMedianLesser': 'lighten(@ColorDataMedian, 20%)',
        '@ColorDataBad': '@ColorStatusWarning',
        '@ColorDataBadText': '@ColorStatusWarningText',
        '@ColorDataBadLesser': 'lighten(@ColorDataBad, 20%)',
        '@ColorDataNeed': 'rgb(113, 118, 133)',
        '@ColorDataNeedSpectrum': 'lighten(@ColorDataNeed, 40 %)',
        '@ColorDataNeedLesser': 'lighten(@ColorDataNeed, 20 %)',
        '@ColorDataAbility': '#B8E986',
        '@ColorDataAbilitySpectrum': 'lighten(@ColorDataAbility, 40 %)',
        '@ColorDataAbilityLesser': 'lighten(@ColorDataAbility, 20 %)',
        '@ColorDataNetWorth': '#B8E986',
        '@ColorDataNetWorthSpectrum': 'lighten(@ColorDataAbility, 40 %)',
        '@ColorDataNetWorthLesser': 'lighten(@ColorDataAbility, 20 %)',
        '@ColorDataIncome': '#B8E986',
        '@ColorDataIncomeSpectrum': 'lighten(@ColorDataIncome, 40 %)',
        '@ColorDataIncomeLesser': 'lighten(@ColorDataIncome, 20 %)',
        '@ColorDataExpense': 'rgb(113, 118, 133)',
        '@ColorDataExpenseSpectrum': 'lighten(@ColorDataExpense, 40 %)',
        '@ColorDataExpenseLesser': 'lighten(@ColorDataExpense, 20 %)',
        '@ColorDataAsset': '#B8E986',
        '@ColorDataAssetSpectrum': 'lighten(@ColorDataAsset, 40 %)',
        '@ColorDataAssetLesser': 'lighten(@ColorDataAsset, 20 %)',
        '@ColorDataLiability': 'rgb(113, 118, 133)',
        '@ColorDataLiabilitySpectrum': 'lighten(@ColorDataLiability, 40 %)',
        '@ColorDataLiabilityLesser': 'lighten(@ColorDataLiability, 20 %)',
        '@ColorDataShortfall': '#F68383',
        '@ColorDataShortfallSpectrum': 'lighten(@ColorDataShortfall, 40 %)',
        '@ColorDataShortfallLesser': 'lighten(@ColorDataShortfall, 20 %)',
        '@ColorDataEducation': 'rgb(68, 140, 203)',
        '@ColorDataMajorPurchase': 'rgb(102, 45, 145)',
        '@ColorDataRetirement': '#192239',
        '@ColorChartStructure': '@ColorContentTextAlpha',
        '@ColorChartLabel': '@ColorContentTextAlpha',
        '@ColorChartDataBackground': '@ColorContentBackground',
        '@ColorChartDataBackgroundLesser': 'rgba(60, 61, 66, 0.1)',
        '@ColorPreviousValueLabel': 'rgb(120, 107, 192)',
        '@ColorPreviousValueLabelDarkBackground': 'rgb(139, 128, 201)',
        '@ColorAddedLabel': 'rgb(45, 174, 195)',
        '@ColorAddedLabelDarkBackground': '@ColorContentAccent',
        '@ColorDeletedLabel': '@ColorStatusWarning',
        '@ColorDeletedLabelDarkBackground': 'rgb(232, 89, 89)',
    };

    onExitClick(): void {
        this.dialogRef.close();
    }

}
